sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t amartynyshyn/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true amartynyshyn/docker-react npm run test
