sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t amartynyshyn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amartynyshyn/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-227915463645"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
